version: "3.8"

services:
  backend:
    image: ${DOCKER_USERNAME}/everybuddy:latest
    container_name: everybuddy-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://everybuddy-mysql.cno2sciake0k.ap-southeast-1.rds.amazonaws.com:3306/everybuddy?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${RDS_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${RDS_PASSWORD}
      AWS_S3_ACCESS_KEY: ${AWS_S3_ACCESS_KEY}
      AWS_S3_SECRET_KEY: ${AWS_S3_SECRET_KEY}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_VALIDITY: ${JWT_VALIDITY}
      JWT_REFRESH_VALIDITY: ${JWT_REFRESH_VALIDITY}
      JWT_TEMP_VALIDITY: ${JWT_TEMP_VALIDITY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_DATABASE_URL: ${FIREBASE_DATABASE_URL}
      FIREBASE_FILE_PATH: ${FIREBASE_FILE_PATH}                 # 순수 볼륨 매핑용
      FIREBASE_CREDENTIALS_PATH: "file:${FIREBASE_FILE_PATH}"   # Spring이 파일을 인식할 수 있도록 환경 변수를 분리
      SERVER_URL: ${SERVER_URL}
      AI_FASTAPI_URL: ${AI_FASTAPI_URL}
    volumes:
      - ./firebase-adminsdk.json:${FIREBASE_FILE_PATH}:ro
    networks:
      - everybuddy-network

networks:
  everybuddy-network:
    driver: bridge
